services:
    - memcached
before_script:
    - chmod 755 ./tests/install-exts
    - ./tests/install-exts
    - composer self-update
    - composer install
language: php
php:
    - 5.4
script:
    - ./vendor/bin/phpunit
notifications:
    email: false
