#!/bin/bash

# this is helpful to compile extension
sudo apt-get install autoconf

# compile manually, because `pecl install apcu-beta` keep asking questions
wget http://pecl.php.net/get/apcu-5.1.18.tgz
tar zxvf apcu-5.1.18.tgz
cd "apcu-5.1.18"
phpize && ./configure && make install && echo "Installed ext/apcu-5.1.18"
