#!/bin/bash

# this script is in a `bin/` folder

if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then
    APCU=4.0.8
else
    APCU=5.1.8
fi

# this is helpful to compile extension
sudo apt-get install autoconf

# compile manually, because `pecl install apcu-beta` keep asking questions
wget http://pecl.php.net/get/apcu-$APCU.tgz
tar zxvf apcu-$APCU.tgz
cd "apcu-${APCU}"
phpize && ./configure && make install && echo "Installed ext/apcu-${APCU}"
